language: cpp
compiler:
    - gcc
before_install:
      yast2-ycp-ui-bindings-dev python-dev
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "doxygen yast2-core-dev yast2-devtools"
script:
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check

